## **Tensor Operations and Manipulation in PyTorch** 

For Laboratory Task 5, we will work with NumPy arrays and PyTorch tensors. The activity focuses on creating reproducible random values, converting between NumPy arrays and tensors, changing tensor data types and shapes, accessing specific elements, performing element-wise operations, and finally performing matrix multiplication.

___

<div class="alert alert-block alert-success" style="font-family: Times New Roman">
    <h4><strong>Laboratory Task 5</strong></h4>

**1. Perform Standard Imports**

```python
import torch
import numpy as np
```
<br>

**2. Create a function called `set_seed()` that accepts `seed: int` as a parameter, this function must return nothing but just set the seed to a certain value.**

```python
def set_seed(seed):
    np.random.seed(seed)
    torch.manual_seed(seed)
```
<br>

**3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the `set_seed()` function and use `42` as the seed parameter.**

```python
set_seed(42)
arr = np.random.randint(0, 5, size=6).astype('int32')

assert np.array_equal(arr, np.array([3,4,2,4,4,1])), "Oops"
print(arr)
```
<br>

**4. Create a tensor "x" from the array above**

```python
x = torch.from_numpy(arr)
```
<br>

**5. Change the dtype of x from `int32` to `int64`**

```python
print('Old:', x.type())

x = x.type(torch.int64)

print('New:', x.type())
```
<br>

**6. Reshape `x` into a 3x2 tensor** <br> There are several ways to do this.

```python
x = x.reshape(3,2)
```
<br>

**7. Return the right-hand column of tensor `x`**

```python
print(x[:,1:])
```
<br>

**8. Without changing x, return a tensor of square values of `x`** <br> There are several ways to do this.

```python
x.pow(2)
print(x)
```
<br>

**9. Create a tensor `y` with the same number of elements as `x`, that can be matrix-multiplied with `x`** <br> Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive). Use 42 as seed. <br> Think about what shape it should have to permit matrix multiplication.

```python
# Code here
set_seed(42)
y = torch.randint(0,5,(2,3))

assert torch.equal(y, torch.tensor([[2, 2, 1],[4, 1, 0]])), "Oops"
print(y)
```
<br>

**10. Find the matrix product of `x` and `y`.**

```python
prod = torch.mm(x,y)
prod
```
</div>

In [2]:
import torch
import numpy as np

First, we create a set_seed() function that sets the random seed for both NumPy and PyTorch. Using the same seed allows us to reproduce the same random values each time the code is executed.

In [3]:

def set_seed(seed):
    np.random.seed(seed)
    torch.manual_seed(seed)

Using a seed of 42, we generate six random integers from 0 to 4 and store them in a NumPy array. The resulting array is [3, 4, 2, 4, 4, 1], which confirms that the seed produces the expected values.

In [4]:
set_seed(42)
arr = np.random.randint(0, 5, size=6).astype('int32')

assert np.array_equal(arr, np.array([3,4,2,4,4,1])), "Oops"
print(arr)

[3 4 2 4 4 1]


We then convert the NumPy array into a PyTorch tensor using torch.from_numpy(). This allows us to continue working with the data using PyTorch operations.

In [5]:
x = torch.from_numpy(arr)

The tensor initially uses a 32-bit integer type. We change it to 64-bit integer, or int64, which PyTorch represents as a LongTensor. The output confirms the change from `torch.IntTensor` to `torch.LongTensor`.

In [6]:
print('Old:', x.type())

x = x.type(torch.int64)

print('New:', x.type())

Old: torch.IntTensor
New: torch.LongTensor


Next, we reshape the tensor from a one-dimensional structure into a 3-by-2 tensor. This gives us a matrix that can be accessed by rows and columns.

In [7]:
x = x.reshape(3,2)

From the reshaped tensor, we extract the right-hand column using column indexing. The resulting values are `[4, 4, 1]`.

In [8]:
print(x[:,1:])

tensor([[4],
        [4],
        [1]])


We then demonstrate an element-wise operation by squaring the values of x. The important point here is that `x.pow(2)` creates the squared values without changing the original tensor. The original tensor remains `[[3, 4], [2, 4], [4, 1]]`.

In [9]:
x.pow(2)
print(x)

tensor([[3, 4],
        [2, 4],
        [4, 1]])


For the matrix multiplication, we create another PyTorch tensor called `y`. Since `x` has a shape of 3 by 2, `y` needs to have a compatible shape of 2 by 3. Using the same seed of 42 produces the matrix `[[2, 2, 1], [4, 1, 0]]`.

In [10]:
# Code here
set_seed(42)
y = torch.randint(0,5,(2,3))

assert torch.equal(y, torch.tensor([[2, 2, 1],[4, 1, 0]])), "Oops"
print(y)

tensor([[2, 2, 1],
        [4, 1, 0]])


Finally, we multiply x and y using PyTorch's matrix multiplication function. Since x is 3 by 2 and y is 2 by 3, the resulting matrix is 3 by 3. The product is `[[22, 10, 3]`, `[20, 8, 2]`, `[12, 9, 4]]`.

In [11]:
prod = torch.mm(x,y)
prod

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])

Overall, this activity demonstrates the basic operations needed when working with NumPy arrays and PyTorch tensors. We created reproducible random data, converted it into a tensor, changed its data type and shape, accessed specific values, performed an element-wise operation, and finally applied matrix multiplication. These operations form the foundation for manipulating tensors in PyTorch and are essential when working with deep learning models.